[tools]
bat = "latest"
eza = "latest"
lazydocker = "latest"
rust = "latest"
starship = "latest"
zoxide = "latest"
ripgrep = "latest"
lazygit = "latest"
glow = "latest"
fd = "latest"
fzf = "latest"
bun = "latest"
"aqua:Schniz/fnm" = "latest"
delta = "latest"
chezmoi = "2.69.4"
difftastic = "latest"
erlang = "latest"
elixir = "latest"
go = "latest"
neovim = "latest"
python = "3.14"
"cargo:scooter" = "latest"
"aqua:sxyazi/yazi" = "latest"
"github:cli/cli" = "latest"
bottom = "latest"
"cargo:worktrunk" = "latest"
opencode = "latest"
"cargo:giff" = "latest"
"nix:solaar" = "latest"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true
