[tools]
bat = "latest"
eza = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
rust = "latest"
starship = "latest"
zoxide = "latest"
ripgrep = "latest"
glow = "latest"
fd = "latest"
fzf = "latest"
bun = "latest"
"aqua:Schniz/fnm" = "latest"
delta = "latest"
chezmoi = "2.62.1"
"aqua:cli/cli" = "latest"
difftastic = "latest"
